name: Build Dev Container
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@master

    - name: Docker Build and Push
      run: |
        echo ${{ secrets.DOCKER_USERNAME }}
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build . -t ${{ secrets.DOCKER_USERNAME }}
        docker push ${{ secrets.DOCKER_USERNAME }}