name: Build Dev Container
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@master

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build and Push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }} .
        docker push ${{ secrets.DOCKER_USERNAME }}